In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
%matplotlib inline

In [2]:
year = 2020
loads = pd.read_csv(f'../data/Prepared data/capitl_{year}.csv')
weather = pd.read_csv(f'../data/Prepared data/{year}_weather_data.csv')

In [6]:
weather

         valid_time_gmt  temp  wspd  pressure  precip_hrly
0      2020-01-01 00:51    40  14.0     29.63          0.0
1      2020-01-01 01:51    40  17.0     29.64          0.0
2      2020-01-01 02:51    40  16.0     29.64          0.0
3      2020-01-01 03:51    39  16.0     29.66          0.0
4      2020-01-01 04:51    38  14.0     29.66          0.0
...                 ...   ...   ...       ...          ...
10251  2020-12-31 19:51    41  12.0     30.31          0.0
10252  2020-12-31 20:51    40   9.0     30.32          0.0
10253  2020-12-31 21:51    40   9.0     30.35          0.0
10254  2020-12-31 22:51    39   9.0     30.38          0.0
10255  2020-12-31 23:51    38   8.0     30.39          0.0

[10256 rows x 5 columns]

In [4]:
loads

                  timestamp    name   ptid       load
0       01/01/2020 00:00:00  CAPITL  61757  1208.4000
1       01/01/2020 00:05:00  CAPITL  61757  1191.0000
2       01/01/2020 00:10:00  CAPITL  61757  1195.5000
3       01/01/2020 00:15:00  CAPITL  61757  1210.9000
4       01/01/2020 00:20:00  CAPITL  61757  1186.3000
...                     ...     ...    ...        ...
107205  12/31/2020 23:35:00  CAPITL  61757  1274.7886
107206  12/31/2020 23:40:00  CAPITL  61757  1279.5598
107207  12/31/2020 23:45:00  CAPITL  61757  1264.3674
107208  12/31/2020 23:50:00  CAPITL  61757  1265.1509
107209  12/31/2020 23:55:00  CAPITL  61757  1256.4921

[107210 rows x 4 columns]

In [12]:
weather = weather.rename(columns={"valid_time_gmt": "timestamp"})

In [13]:
# weather['date'] = weather.date.apply(lambda x: pd.to_datetime(x).date())
# weather['timeest'] = weather.Time.apply(lambda x: pd.to_datetime(x).time())
# foo = weather[['date', 'timeest']].astype(str)
# weather['timestamp'] = pd.to_datetime(foo['date'] + ' ' + foo['timeest'])
print(weather.columns)
weather['timestamp'] = weather.timestamp.apply(lambda x: pd.to_datetime(x))
loads['timestamp'] = loads.timestamp.apply(lambda x: pd.to_datetime(x))

Index(['timestamp', 'temp', 'wspd', 'pressure', 'precip_hrly'], dtype='object')

In [14]:
weather

                timestamp  temp  wspd  pressure  precip_hrly
0     2020-01-01 00:51:00    40  14.0     29.63          0.0
1     2020-01-01 01:51:00    40  17.0     29.64          0.0
2     2020-01-01 02:51:00    40  16.0     29.64          0.0
3     2020-01-01 03:51:00    39  16.0     29.66          0.0
4     2020-01-01 04:51:00    38  14.0     29.66          0.0
...                   ...   ...   ...       ...          ...
10251 2020-12-31 19:51:00    41  12.0     30.31          0.0
10252 2020-12-31 20:51:00    40   9.0     30.32          0.0
10253 2020-12-31 21:51:00    40   9.0     30.35          0.0
10254 2020-12-31 22:51:00    39   9.0     30.38          0.0
10255 2020-12-31 23:51:00    38   8.0     30.39          0.0

[10256 rows x 5 columns]

In [17]:
from sklearn.neighbors import NearestNeighbors

def find_nearest(group, match, groupname):
    nbrs = NearestNeighbors(n_neighbors=1).fit(match['timestamp'].values[:, None])
    dist, ind = nbrs.kneighbors(group['timestamp'].values[:, None])

    group['nearesttime'] = match['timestamp'].values[ind.ravel()]
    return group

In [18]:
loads = find_nearest(loads,weather,'timestamp')

In [19]:
loads

                 timestamp    name   ptid       load         nearesttime
0      2020-01-01 00:00:00  CAPITL  61757  1208.4000 2020-01-01 00:51:00
1      2020-01-01 00:05:00  CAPITL  61757  1191.0000 2020-01-01 00:51:00
2      2020-01-01 00:10:00  CAPITL  61757  1195.5000 2020-01-01 00:51:00
3      2020-01-01 00:15:00  CAPITL  61757  1210.9000 2020-01-01 00:51:00
4      2020-01-01 00:20:00  CAPITL  61757  1186.3000 2020-01-01 00:51:00
...                    ...     ...    ...        ...                 ...
107205 2020-12-31 23:35:00  CAPITL  61757  1274.7886 2020-12-31 23:51:00
107206 2020-12-31 23:40:00  CAPITL  61757  1279.5598 2020-12-31 23:51:00
107207 2020-12-31 23:45:00  CAPITL  61757  1264.3674 2020-12-31 23:51:00
107208 2020-12-31 23:50:00  CAPITL  61757  1265.1509 2020-12-31 23:51:00
107209 2020-12-31 23:55:00  CAPITL  61757  1256.4921 2020-12-31 23:51:00

[107210 rows x 5 columns]

In [21]:
full = loads.merge(weather, left_on='nearesttime', right_on='timestamp')
print(full.columns)
print(full)

full = full[['timestamp_x', 'load', 'nearesttime', 'temp', 'wspd', 'pressure', 'precip_hrly']].rename(columns={'timestamp_x': 'timestamp', 'nearesttime':'weathertime'})

Index(['timestamp_x', 'name', 'ptid', 'load', 'nearesttime', 'timestamp_y',
       'temp', 'wspd', 'pressure', 'precip_hrly'],
      dtype='object')
               timestamp_x    name   ptid       load         nearesttime  \
0      2020-01-01 00:00:00  CAPITL  61757  1208.4000 2020-01-01 00:51:00
1      2020-01-01 00:05:00  CAPITL  61757  1191.0000 2020-01-01 00:51:00
2      2020-01-01 00:10:00  CAPITL  61757  1195.5000 2020-01-01 00:51:00
3      2020-01-01 00:15:00  CAPITL  61757  1210.9000 2020-01-01 00:51:00
4      2020-01-01 00:20:00  CAPITL  61757  1186.3000 2020-01-01 00:51:00
...                    ...     ...    ...        ...                 ...
107224 2020-12-31 23:35:00  CAPITL  61757  1274.7886 2020-12-31 23:51:00
107225 2020-12-31 23:40:00  CAPITL  61757  1279.5598 2020-12-31 23:51:00
107226 2020-12-31 23:45:00  CAPITL  61757  1264.3674 2020-12-31 23:51:00
107227 2020-12-31 23:50:00  CAPITL  61757  1265.1509 2020-12-31 23:51:00
107228 2020-12-31 23:55:00  CAPITL  61757  1256.4921 2020-12-31 23:51:00

               timestamp_y  temp  wspd  pressure  precip_hrly
0      2020-01-01 00:51:00    40  14.0     29.63          0.0
1      2020-01-01 00:51:00    40  14.0     29.63          0.0
2      2020-01-01 00:51:00    40  14.0     29.63          0.0
3      2020-01-01 00:51:00    40  14.0     29.63          0.0
4      2020-01-01 00:51:00    40  14.0     29.63          0.0
...                    ...   ...   ...       ...          ...
107224 2020-12-31 23:51:00    38   8.0     30.39          0.0
107225 2020-12-31 23:51:00    38   8.0     30.39          0.0
107226 2020-12-31 23:51:00    38   8.0     30.39          0.0
107227 2020-12-31 23:51:00    38   8.0     30.39          0.0
107228 2020-12-31 23:51:00    38   8.0     30.39          0.0

[107229 rows x 10 columns]

In [22]:
# full.to_csv('full2012.csv',encoding='utf-8-sig', index=False)

In [23]:
# full = pd.read_csv('full2012.csv')

In [24]:
pday = pd.Timedelta('1 day')

def get_prev_days(x, n_days):
    try:
        lo = full[full.timestamp == x - n_days*pday].load.values[0]
    except:
        lo = full[full.timestamp == x].load.values[0]
    return lo

In [25]:
full['dow'] = full.timestamp.apply(lambda x: x.dayofweek)
full['doy'] = full.timestamp.apply(lambda x: x.dayofyear)
full['day'] = full.timestamp.apply(lambda x: x.day)
full['month'] = full.timestamp.apply(lambda x: x.month)
full['hour'] = full.timestamp.apply(lambda x: x.hour)
full['minute'] = full.timestamp.apply(lambda x: x.hour*60 + x.minute)
full['year'] = full.timestamp.apply(lambda x: x.year)

# full['t_m24'] = full.timestamp.apply(get_prev_days, args=(1,))
# full['t_m48'] = full.timestamp.apply(get_prev_days, args=(2,))
# full['tdif'] = full['load'] - full['t_m24']

In [13]:
# full['Temperature'] = full['Temperature'].map(lambda x: x[:-2])
# full['Dew Point'] = full['Dew Point'].map(lambda x: x[:-2])
# full['Humidity'] = full['Humidity'].map(lambda x: x[:-2])
# full['Pressure'] = full['Pressure'].map(lambda x: x[:-3])
# full['Wind Speed'] = full['Wind Speed'].map(lambda x: x[:-4])
# full['precipitation'] = full['precipitation'].map(lambda x: x[:-3])

In [26]:
full

,timestamp,load,weathertime,temp,wspd,pressure,precip_hrly,dow,doy,day,month,hour,minute
0,2020-01-01 00:00:00,1208.4000,2020-01-01 00:51:00,40,14.0,29.63,0.0,2,1,1,1,0,0
1,2020-01-01 00:05:00,1191.0000,2020-01-01 00:51:00,40,14.0,29.63,0.0,2,1,1,1,0,5
2,2020-01-01 00:10:00,1195.5000,2020-01-01 00:51:00,40,14.0,29.63,0.0,2,1,1,1,0,10
3,2020-01-01 00:15:00,1210.9000,2020-01-01 00:51:00,40,14.0,29.63,0.0,2,1,1,1,0,15
4,2020-01-01 00:20:00,1186.3000,2020-01-01 00:51:00,40,14.0,29.63,0.0,2,1,1,1,0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107224,2020-12-31 23:35:00,1274.7886,2020-12-31 23:51:00,38,8.0,30.39,0.0,3,366,31,12,23,1415
107225,2020-12-31 23:40:00,1279.5598,2020-12-31 23:51:00,38,8.0,30.39,0.0,3,366,31,12,23,1420
107226,2020-12-31 23:45:00,1264.3674,2020-12-31 23:51:00,38,8.0,30.39,0.0,3,366,31,12,23,1425
107227,2020-12-31 23:50:00,1265.1509,2020-12-31 23:51:00,38,8.0,30.39,0.0,3,366,31,12,23,1430
107228,2020-12-31 23:55:00,1256.4921,2020-12-31 23:51:00,38,8.0,30.39,0.0,3,366,31,12,23,1435

In [27]:
full.to_csv(f'{year}_features.csv',encoding='utf-8-sig', index=False)

In [3]:
# full = pd.read_csv('full2011-2020_features.csv')

In [5]:
# full['timestamp'] = full.timestamp.apply(lambda x: pd.to_datetime(x))
full['year'] = full.timestamp.apply(lambda x: x.year)

In [6]:
full.to_csv('full2011-2020_features.csv',encoding='utf-8-sig', index=False)